spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://localhost:8888

#spring:
#  application:
#    name: discovery-server
#server:
#  port: 8761
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
